### ISSUE TITLE
model_KITTI_exp_CP2.pth

### ISSUE THREAD

**Issue by mjanddy** [chanlilong/4D_NET_pytorch#1]
Hi,how can I get the model  for "model_KITTI_exp_CP2.pth"?

**Comment by chanlilong** [comment]
https://lchan017.asuscomm.com/s/4ytTaXQNmCLDzRA
password:4dnetpytorch

**Comment by chanlilong** [comment]
Let me know if you face any issues,ill try to address them

**Comment by mjanddy** [comment]
> me kno

ok,thanks!
